name: spring-6-microservices
services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: restdb
      MYSQL_ROOT_PASSWORD: password
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping" ,"-h", "localhost"]
      timeout: 30s
      retries: 10
  auth-server:
    container_name: auth-server
    image: spring-6-auth-server:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9000:9000"
  rest-mvc:
    container_name: rest-mvc
    image: spring-6-rest-mvc:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9000
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      auth-server:
        condition: service_started
    ports:
      - "8081:8080"
  gateway:
    container_name: gateway
    image: spring-6-cloud-gateway:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    depends_on:
      auth-server:
        condition: service_started
      rest-mvc:
        condition: service_started
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_started
    ports:
      - 8082:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  cold-service:
    container_name: cold-service
    image: spring-6-cold-service:0.0.1-SNAPSHOT
    expose:
      - 8080
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_started
  cool-service:
    container_name: cool-service
    image: spring-6-cool-service:0.0.1-SNAPSHOT
    expose:
      - 8080
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_started
  ice-cold-service:
    container_name: ice-cold-service
    image: spring-6-ice-cold-service:0.0.1-SNAPSHOT
    expose:
      - 8080
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_started